on:
  push:
    branches: [main]
  pull_request:

name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Flatpak with flatpak-builder
      run: |
        flatpak-builder --repo=./repo/repo build-dir org.flatpak.Hello.yml
    
    - name: Create Flatpak repository metadata
      run: |
        flatpak build-update-repo --prune --generate-static-deltas ./repo/repo

    - name: Write .flatpakrepo file
      run: |
          set -e
          echo "[Flatpak Repo]
          Title=https://grisha765.github.io/my_flatpak_repo/repo
          Url=https://grisha765.github.io/my_flatpak_repo/repo > repo/${{ github.repository_owner }}.flatpakrepo
    
    - name: Deploy Repo
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: repo
          enable_jekyll: true
          force_orphan: true

