on:
  push:
    branches-ignore: 
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select manifest'
        required: true
        default: 'io.github.grisha765.Hello'

name: Build manifest

env:
    PAGES_REPO_URL: ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
    NGINX_REPO_URL: ergolyam.line.pm/flatpak/
    FLATPAK_HISTORY_LEN: 0
    FLATPAK_DELTAS: true
    FLATPAK_JOBS: 6
     
    FLATPAK_BUILD: build-dir
    PAGES_REPO: repo-dir
    NGINX_REPO: /usr/share/nginx/html

jobs:
  flatpak:
    runs-on: larga-serv
    steps:
    - name: Determine Branch
      id: branch
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
        else
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Import GPG-key
      id: gpg-key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Prepare GPG-pubkey
      run: |
        set -e
        gpg --export ${{ steps.gpg-key.outputs.fingerprint }} > pubkey.gpg

    - name: Install flatpak
      run: |
        set -e
        sudo apt update -y
        sudo apt install -y flatpak flatpak-builder
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    
    - name: Build Flatpak with flatpak-builder
      run: |
        set -e
        git config --global protocol.file.allow always
        mkdir -p ${{ env.NGINX_REPO }}/repo
        flatpak-builder --install-deps-from=flathub --install-deps-only --user /dev/null "$FILE"
        flatpak-builder --ccache --jobs=${{ env.FLATPAK_JOBS }} --force-clean --disable-updates --sandbox --gpg-sign=${{ steps.gpg-key.outputs.fingerprint }} --repo=${{ env.NGINX_REPO }}/repo ${{ env.FLATPAK_BUILD }} "$FILE"
      env:
        FILE: ${{ steps.branch.outputs.branch }}.yml
    
    - name: Create Flatpak repository metadata
      run: |
        set -e
        mkdir -p ${{ env.NGINX_REPO }}/repo/refs/remotes ${{ env.NGINX_REPO }}/repo/refs/mirrors
        touch ${{ env.NGINX_REPO }}/repo/refs/remotes/.gitkeep ${{ env.NGINX_REPO }}/repo/refs/mirrors/.gitkeep
        flatpak build-update-repo --no-update-summary --prune --prune-depth=${{ env.FLATPAK_HISTORY_LEN }} ${{ env.NGINX_REPO }}/repo
        flatpak build-update-repo --gpg-sign=${{ steps.gpg-key.outputs.fingerprint }} --gpg-import=pubkey.gpg --generate-static-deltas ${{ env.NGINX_REPO }}/repo

    - name: Write .flatpakrepo file
      run: |
        set -e
        cat > ${{ env.NGINX_REPO }}/${{ github.repository_owner }}.flatpakrepo << EOF 
        [Flatpak Repo]
        Title=${{ env.NGINX_REPO_URL }}
        Url=https://${{ env.NGINX_REPO_URL }}repo/
        GPGKey=$(cat pubkey.gpg | base64 --wrap=0)"
        EOF
