on:
  push:
    branches: [main]
  pull_request:

name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Flatpak with flatpak-builder
      run: |
        flatpak-builder --repo=repo build-dir org.flatpak.Hello.yml
    
    - name: Create Flatpak repository metadata
      run: |
        flatpak build-update-repo --prune --generate-static-deltas repo
    
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push to gh-pages
      run: |
        git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        rsync -av --delete repo/ gh-pages/repo/
        cd gh-pages
        touch .nojekyll
        git add .
        git commit -m "Update Flatpak repository"
        git push https://github.com/${{ github.repository }} gh-pages

