name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  APP_ID: org.flatpak.Hello
  MANIFEST_PATH: ${{ github.workspace }}/${{ env.APP_ID }}.yaml
  BUNDLE: "${{ env.APP_ID }}.flatpak"
  DOCKER_IMAGE: "ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run external data checker
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker
        with:
          entrypoint: ""
        run: |
          /app/flatpak-external-data-checker --update --commit-only ${{ env.MANIFEST_PATH }}
          
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" || true

  flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flatpak build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder

      - name: Pull Docker image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}

      - name: Add Flathub repository
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Import GPG keys
        run: |
          echo ${{ secrets.GPG_PRIVATE_KEY }} | gpg --import --batch
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
          echo "${{ secrets.GPG_PASSPHRASE }}" | /usr/libexec/gpg-preset-passphrase --preset ${{ secrets.GPG_KEY_GREP }}

      - name: Build Flatpak
        run: |
          flatpak-builder build --user --install-deps-from=flathub --gpg-sign=${{ secrets.GPG_KEY_ID }} --disable-rofiles-fuse --disable-updates --force-clean --repo=repo ${{ env.MANIFEST_PATH }}
          flatpak build-bundle --gpg-sign=${{ secrets.GPG_KEY_ID }} repo ${{ env.BUNDLE }} --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo ${{ env.APP_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flatpak-repo
          path: repo

  deploy:
    runs-on: ubuntu-latest
    needs: flatpak
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup rsync
        run: |
          sudo apt-get update && sudo apt-get install -y rsync

      - name: Prepare GitHub Pages
        run: |
          mkdir public || true
          rsync -av --exclude='public' --exclude='.git' repo/ public
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


